# Generated by Django 3.0.6 on 2020-07-22 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(verbose_name='Description')),
                ('is_published', models.BooleanField(verbose_name='Users can see it and answer it')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyResponse')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(blank=True, help_text="The choices field is only used if the question type\n    if the question type is 'radio' or 'select' provide a comma-separated list of\n    options for this question .", max_length=500, null=True, verbose_name='Choices')),
                ('question_type', models.CharField(choices=[('text', 'Long text (multiple line)'), ('short-text', 'Short text (one line)'), ('radio', 'Radio Select'), ('select', 'Empty')], default='text', max_length=200, verbose_name='Type')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.Survey', verbose_name='Survey')),
            ],
        ),
    ]
