# Generated by Django 3.0.6 on 2020-07-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('survey', 'order'), 'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(default='foo', max_length=500, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
