# Generated by Django 3.0.6 on 2020-07-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20200722_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Users can see it and answer it'),
        ),
    ]
