# Generated by Django 3.0.6 on 2020-07-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20200722_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Choices'),
        ),
    ]
