# Generated by Django 3.0.6 on 2020-07-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20200722_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.CharField(blank=True, help_text='Provide a comma-separated list\n    of options for this question.', max_length=500, null=True, verbose_name='Choices'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Long text (multiple line)'), ('short-text', 'Short text (one line)'), ('radio', 'Radio Select')], default='text', max_length=200, verbose_name='Type'),
        ),
    ]
