# Generated by Django 3.0.6 on 2020-07-24 18:13

from django.db import migrations
import survey.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20200722_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='content',
            field=survey.fields.JSONField(blank=True, null=True, verbose_name='Response'),
        ),
    ]
