# Generated by Django 3.0.6 on 2020-07-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_surveyresponse_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='response_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='response_id'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.CharField(blank=True, help_text='Provide a comma-separated list\n    of options for this question.', max_length=100, null=True, verbose_name='Choices'),
        ),
    ]
