# Generated by Django 3.0.6 on 2020-07-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20200725_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='response_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='response_id'),
        ),
    ]
