# Generated by Django 3.0.6 on 2020-07-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20200725_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='session_key'),
        ),
    ]
